# Generated by Django 5.2 on 2025-05-16 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamentos', '0003_alter_alojamentos_id'),
        ('app', '__first__'),
        ('obras', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('alojamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamentos.alojamentos')),
                ('obra_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obras')),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario')),
                ('veiculo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculos')),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
    ]
