# Generated by Django 5.2 on 2025-06-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamentos', '0002_alojamentos_quantidade_de_vagas'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='alojamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='alojamentos.alojamentos'),
        ),
    ]
