# Generated by Django 5.2 on 2025-05-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='alojamento_id',
            new_name='alojamento',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='obra_id',
            new_name='obra',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='veiculo_id',
            new_name='veiculo',
        ),
    ]
