# Generated by Django 5.2 on 2025-07-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionarios_alojamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionarios',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='veiculo',
        ),
    ]
