# Generated by Django 5.2 on 2025-07-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0002_veiculos_ativo_veiculos_latitude_veiculos_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_paradas', models.JSONField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculos')),
            ],
            options={
                'db_table': 'rotas_otimizadas',
            },
        ),
    ]
