# Generated by Django 5.2 on 2025-07-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
        ('rotas', '0001_initial'),
        ('veiculos', '0002_veiculos_ativo_veiculos_latitude_veiculos_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='descricao_transporte',
            field=models.CharField(default='', help_text='Nome da operação. Ex: Transporte Obra X 05/07/2025', max_length=255),
        ),
        migrations.AddField(
            model_name='rota',
            name='distancia_total_metros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='duracao_total_segundos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='obra_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='obras.obras'),
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='ordem_paradas',
            field=models.JSONField(help_text='Detalhes completos da rota, incluindo visitas, tempos e distâncias'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculos'),
        ),
    ]
