# Generated by Django 5.2 on 2025-07-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_rota_descricao_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='tipo_trecho',
            field=models.CharField(choices=[('IDA', 'Ida'), ('VOLTA', 'Volta')], default='IDA', max_length=5),
        ),
    ]
