# Generated by Django 5.2 on 2025-07-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0003_rota_tipo_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='polyline',
            field=models.TextField(blank=True, help_text='Polyline codificada para desenhar a rota no mapa', null=True),
        ),
    ]
