# Generated by Django 5.2 on 2025-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculos_ativo_veiculos_latitude_veiculos_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
