# Generated by Django 5.2 on 2025-05-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alojamentos',
            table='alojamentos',
        ),
    ]
