# Generated by Django 5.2 on 2025-06-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamentos',
            name='quantidade_de_vagas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
