# Generated by Django 5.2 on 2025-05-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamentos', '0002_alter_alojamentos_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
